// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://noezhadpvnfftotwgard.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vZXpoYWRwdm5mZnRvdHdnYXJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MTk2NzUsImV4cCI6MjA2NDA5NTY3NX0.arJjcZ873-YOL7-jR6e3n3ndHieePlIcv57YdF-ZbrY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);